# Age Calculation netlify.toml

[build]
  publish = "profile-card-component-main"  # Adjust based on your project structure

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = true
