
# Age Calculation netlify.toml

[build]
  command = "echo 'Build command not required for a JavaScript project'"
  publish = "age-calculator-app-main"  # Adjust based on your project structure

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = true

